---
- name: 安装httpd服务  
  hosts: all  
  become: yes  
  tasks:  
    - name: 安装httpd软件包  
      yum:  
        name: httpd  
        state: present  
  
    - name: 启动httpd服务并设置开机自启  
      systemd:  
        name: httpd  
        state: started  
        enabled: yes  
  
    - name: 防火墙开放80端口  
      firewalld:  
        port: 80/tcp  
        permanent: yes  
        state: enabled  
        immediate: yes  
  
    - name: 检查httpd服务状态  
      systemd:  
        name: httpd  
        state: active  
      register: httpd_status  
      failed_when: httpd_status.status != 200  
  
    - name: 输出httpd服务状态信息  
      debug:  
        msg: "httpd服务已安装并正在运行。"

